#!/bin/bash
# NOTE: SCVD requires Kaggle CLI + credentials configured (~/.kaggle/kaggle.json)
mkdir -p data
kaggle datasets download -d toluwaniaremu/smartcity-cctv-violence-detection-dataset-scvd -p data --unzip

echo ""
echo "----------------------------------------------------------------------"
echo "Weapon-detection sources (Roboflow -- requires ROBOFLOW_API_KEY env var,"
echo "get a free key at roboflow.com -> Settings -> API):"
echo ""
echo "  python - <<'PYEOF'"
echo "from roboflow import Roboflow"
echo "import os"
echo "rf = Roboflow(api_key=os.environ['ROBOFLOW_API_KEY'])"
echo "sources = ["
echo "    ('mohammadreza-anvari-h6ase', 'cctv-gun-detector', 1),"
echo "    ('weapondetection-um7tj', 'gun-and-knife-detection-system', 13),"
echo "    ('mahad-ahmed', 'gun-and-knife-detection', 1),"
echo "    ('yolo-4jb2u', 'weapon-detection-kuoas', 1),"
echo "]"
echo "for ws, proj, ver in sources:"
echo "    rf.workspace(ws).project(proj).version(ver).download('yolov8', location=f'data/{proj}')"
echo "PYEOF"
echo ""
echo "US-Seville (Mock Attack + Unity Synthetic), Hugging Face, no auth needed:"
echo "  wget https://huggingface.co/datasets/jsalazar/US-Real-time-gun-detection-in-CCTV-An-open-problem-dataset/resolve/main/weapons_images_2fps.zip -O data/mock_attack.zip"
echo "  wget https://huggingface.co/datasets/jsalazar/US-Real-time-gun-detection-in-CCTV-An-open-problem-dataset/resolve/main/Unity/split-2500.zip -O data/unity_synthetic.zip"
echo ""
echo "RLVS (Real Life Violence Situations), freely downloadable, no agreement required:"
echo "  kaggle datasets download -d mohamedmustafa/real-life-violence-situations-dataset -p data --unzip"
echo ""
echo "RWF-2000 and NTU CCTV-Fights require signed data-access agreements."
echo "See docs/METHODOLOGY.md for the request process -- not automated here."
echo "----------------------------------------------------------------------"
